### ISSUE TITLE
Update the runtime

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/io.github.Hexchat#13]
Consider updating the runtime used by this Flatpak to `45`.

**Comment by TingPing** [comment]
Fixed by e31a298a8308aea06480b281061c3887f7f79bba

**Comment by AsciiWolf** [comment]
Thanks! The [OTR](https://github.com/flathub/io.github.Hexchat.Plugin.OTR) and [Perl](https://github.com/flathub/io.github.Hexchat.Plugin.Perl) plugins should probably also be updated.

**Comment by TingPing** [comment]
- https://github.com/flathub/io.github.Hexchat.Plugin.OTR/pull/7
- https://github.com/flathub/io.github.Hexchat.Plugin.Perl/pull/7
