### ISSUE TITLE
alert sounds no longer working after upgrade to Fedora 28

### ISSUE THREAD

**Issue by miabbott** [flathub/io.github.Hexchat#2]
I'm using Fedora Atomic Workstations and after upgrading to the release based on Fedora 28, my flatpak install of `hexchat` lost the ability to play sounds.  As best as I can remember, I've not made any changes to the default configuration for sounds + events.  And I'm fairly certain this worked with the Fedora 27 version of Atomic Workstation.

Going into Preferences > Chatting > Sounds, trying to play a sound associated with an event, like 'Keyword', I get a dialog saying

```
Cannot read sound file:
/usr/share/sounds/gnome/default/alerts/drip.ogg
```

On the filesystem of the host, that file does exist and the permissions do not seem to be restricting access:

```$ ls -la /usr/share/sounds/gnome/default/alerts/
total 68
drwxr-xr-x. 2 root root    72 Dec 31  1969 .
drwxr-xr-x. 3 root root    20 Dec 31  1969 ..
-rw-r--r--. 3 root root 13322 Dec 31  1969 bark.ogg
-rw-r--r--. 5 root root  8495 Dec 31  1969 drip.ogg
-rw-r--r--. 3 root root 18999 Dec 31  1969 glass.ogg
-rw-r--r--. 3 root root 20011 Dec 31  1969 sonar.ogg
```

I'm able to successfully play the file using `totem`.

Some corresponding info:

```
$ rpm -q flatpak ostree
flatpak-0.11.7-1.fc28.x86_64
ostree-2018.5-1.fc28.x86_64
$ flatpak info io.github.Hexchat/x86_64/stable
Ref: app/io.github.Hexchat/x86_64/stable
ID: io.github.Hexchat
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-03-24 17:19:39 +0000
Subject: Update lgi (c32ea9ac)
Commit: 5f8d7cf51f580cce3cddf2a786dc8a88716cd65ba825ad59056a21085f5bd53d
Parent: 0272d4f1490fffa39977b6c1f0a9f283f5fb94e0edf3e47d18e4035ff34eaf8a
Location: /var/lib/flatpak/app/io.github.Hexchat/x86_64/stable/5f8d7cf51f580cce3cddf2a786dc8a88716cd65ba825ad59056a21085f5bd53d
Installed size: 2.4 MB
Runtime: org.gnome.Platform/x86_64/3.26
```

**Comment by TingPing** [comment]
> On the filesystem of the host,

What is on the host doesn't matter, that file isn't in the sandbox so it doesn't exist. A simple solution is to copy that file to `~/.var/app/io.github.Hexchat/config/hexchat/sounds`

**Comment by miabbott** [comment]
Ah, of course!  Unfortunately, even after copying the files, there is no error dialog, but also no sound produced.

**Comment by miabbott** [comment]
Yup, confirmed working for me with the update.  Thanks!
