### ISSUE TITLE
Fatal Python error

### ISSUE THREAD

**Issue by memnoth** [flathub/io.github.Hexchat#5]
The following error always occurs when exiting Hexchat.
```
Gtk-Message: 10:37:22.929: Failed to load module "pk-gtk-module"
Gtk-Message: 10:37:22.929: Failed to load module "canberra-gtk-module"
Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters
```

Is there any way to get logs in details? 

Fedora 29 Workstation
Flatpak: 1.2.3
Hexchat: Up to date

**Comment by TingPing** [comment]
This is https://github.com/hexchat/hexchat/issues/2237

**Comment by memnoth** [comment]
@TingPing Thank you!
